name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: jekyll-gh-pages@v2
        with:
          src: .
          branch: gh-pages
          force: true
